services:

  registry-ui:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REGISTRY_URL=${REGISTRY_URL}
      - REGISTRY_TYPE=${REGISTRY_TYPE}
      - REGISTRY_REPO=${REGISTRY_REPO}
      - REGISTRY_SSL_VERIFY=${REGISTRY_SSL_VERIFY}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - REGISTRY_USERNAME=${REGISTRY_USERNAME}
      - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}