services:

  registry-ui:
    build: .
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - "${PORT:-8000ok}:8000"
    environment:
      # registry settings
      - REGISTRY_URL=${REGISTRY_URL}
      - REGISTRY_TYPE=${REGISTRY_TYPE}
      - REGISTRY_REPO=${REGISTRY_REPO}
      - REGISTRY_SSL_VERIFY=${REGISTRY_SSL_VERIFY}
      # application settings
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      # Authentication credentials
      - REGISTRY_USERNAME=${REGISTRY_USERNAME}
      - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
      # Admin mode
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
